apiVersion: extensions/v1beta1  # Deprecated API version
kind: Deployment
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api
        image: node:16
        env:
        - name: DB_HOST
          value: "production-db"  # Different from config1
        - name: DB_PORT 
          value: "5432"           # Same as config1 - redundant
        - name: JWT_SECRET
          value: "${JWT_SECRET}"  # Placeholder - should not trigger secret warning
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"       # Same as config1 - redundant
            cpu: "300m"
          requests:
            memory: "256Mi"       # Same as config1 - redundant  
            cpu: "150m" 